version: '3.8'

services:
  # NestJS应用服务
  app:
    build: .
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=your-super-secret-jwt-key-here-docker
      - JWT_EXPIRES_IN=7d
    volumes:
      - ./logs:/app/logs
      - ./noa.db:/app/noa.db
    restart: unless-stopped
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge
