version: '3.8'

services:
  # NestJS应用服务
  app:
    build: .
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=wangfang
      - JWT_EXPIRES_IN=7d
    volumes:
      - ./logs:/app/logs
      - ./noa.db:/app/noa.db:rw
      - node_modules:/app/node_modules # 持久化node_modules
    restart: unless-stopped
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  node_modules: # 定义命名卷
